/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package githubcopilot.weatherforecastapp;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;

class AppTest {
    @Test void appHasgetWeatherForecast() throws IOException {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getWeatherForecast(null, null), "app must have a getWeatherForecast() method");
       
    }
}
